increase build number
conda-forge/libprotobuf-feedstock pull request #216
Opened 2024-04-04 16:38 UTC by ekomarova

This PR was created simply to rebuild libprotobuf with a new zlib 1.3, in order to get rid of such a restriction
```
libprotobuf 5.26.1 h08a7969_0
-----------------------------
file name   : libprotobuf-5.26.1-h08a7969_0.conda
dependencies:
  - libzlib >=1.2.13,<1.3.0a0
```
what does not allow to install libprotobuf with zlib 1.3

* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-04-04 16:38 UTC, ekomarova commented
@conda-forge-admin, please rerender

2024-04-04 17:23 UTC, jjerphan submitted a review, later dismissed

2024-04-04 18:53 UTC, h-vetinari requested changes
This is the wrong place to tackle this. We need to figure out whether the ABI in zlib changed from 1.2 to 1.3, and then either migrate or patch the repodata. See https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5443

2024-04-05 11:15 UTC, ekomarova commented
> This is the wrong place to tackle this. We need to figure out whether the ABI in zlib changed from 1.2 to 1.3, and then either migrate or patch the repodata. See [conda-forge/conda-forge-pinning-feedstock#5443](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5443)

What do you think about doing what for example libxml2 does https://github.com/conda-forge/libxml2-feedstock/pull/115? And build it for 2 versions

2024-04-05 17:20 UTC, h-vetinari commented
> What do you think about doing what for example libxml2 does [...] and build it for 2 versions

It's not sustainable. You would need to rebuild every protobuf-dependent package twice, and soon all of conda-forge. If zlib 1.3 is important to you, please direct your energy to https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5443.

2024-06-04 04:24 UTC, h-vetinari commented
This PR is obsolete, libprotobuf can be used with zlib 1.3 now.

2024-06-04 04:24 UTC, closed without merging